### ISSUE TITLE
Column names don't match what is seen in Data Studio

### ISSUE THREAD

**Issue by ltirrell** [FlipsideCrypto/sdk#25]
`columnNames` returned by the Python SDK are all lowercase. In the Data Studio, they are uppercase, or case can be made explicit using double quotes. The behavior of shroomDK v1.0.2 matched the data studio. This change effects downstream processing, which is case sensitive for column names.

Is it possible to re-enable the old behavior?

## Example:
```sql
select 
  block_timestamp::date as "Date",
  count(distinct tx_id) as tx_count,
  program_id
from
  solana.core.fact_events
where
  block_timestamp::date = '2023-05-21'
group by
  program_id,
  "Date"
```
### Expected results
Column names: 
- `Date`
- `TX_COUNT`
- `PROGRAM_ID`

### Actual results
Column names: 
- `date`
- `tx_count`
- `program_id`
- `__row_index`

Note, an additional `__row_index` column is included even though it wasn't included in the query

**Comment by jfmyers** [comment]
Hi @ltirrell thanks for sharing this!

Unfortunatley we cannot change the column name format. This has been live and in production since very early May, and with a larger number of users currently on the API, changing the format at this point would potentially break a large volume of applications/integrations. 

I realize this is inconvenient, but would consider this one of the small steps in upgrading from the legacy ShroomDK system to the new system.

`__row_index` is critical and was added to support features such as pagination and features not yet exposed via the SDK but supported by DuckDB (what the new query engine uses under the hood)
